moses_app/dashboard/views.py
# moses_app/dashboard/views.py

from flask import Blueprint, render_template, redirect, url_for, session
from flask_login import login_user, login_required, logout_user
import flask_login
from moses_app import db
from moses_app.models import HospitalInfo, Hospitals
from moses_app import models
import datetime
import json
import pandas as pd

dashboard_blueprint = Blueprint('dashboard', __name__,
                                        template_folder='templates/dashboard')

@dashboard_blueprint.route('/dashboard', methods=['GET', 'POST'])
def dashboard():

    sql_query = """
    SELECT
        hospital_name
        , status
        , hospital_address
        , hospital_contact_num

        , num_confirmed_covid
        , num_pui

        , request_supplies
        , num_covid_kits
        , num_face_masks
        , num_surgical_gloves
        , num_alcohol
        , num_face_shield
        , num_hoods
        , num_shoe_covers
        , num_respirators

        , num_doctors_for_covid
        , num_nurses_for_covid
        , num_medstaff_for_covid

        , capacity_quarantine
        , notes

        , hospital_website
        , hospital_email
        , timestamp

    FROM HospitalInfo a
    LEFT JOIN Hospitals b
    ON a.hospital_id = b.id
    """

    table = db.engine.execute(sql_query)
    table = [row for row in table]

    columns = ['Hospital Name', 'Status', 'Address', 'Contact Num',
    'Num Confirmed COVID', 'Num PUI', 'Supplies Requested', 'Num COVID Kits',
    'Num Face Mask', 'Num Surgical Gloves', 'Num Alcohol', 'Num Face Shield',
    'Num Hoods', 'Num Shoe Covers', 'Num Respirators',
    'Num Doctors Assigned', 'Num Nurses Assigned', 'Num Med Staff Assigned',
    'Capacity to Quarantine', 'Notes',
    'Website',  'Email', 'Last Updated']

    df = pd.DataFrame(table)
    print(len(columns))
    print(df.shape)
    df.columns = columns


    df = df.groupby(by='Hospital Name').last().T.reset_index(drop=False)
    df.rename(columns={'index':'Hospital Name'}, inplace=True)
    df = df.T.reset_index().T

    num_cols = len(df.columns)
    df.columns = range(num_cols)
    df.to_csv('table.csv')

    table = df.to_dict()
    table = [{str(k):str(list(v.values())[i]) for k,v in table.items()} for i in range(len(df))]
    hospital_tables = table

    return render_template('dashboard.html',
                    hospital_tables=json.dumps(hospital_tables),
                    num_cols=num_cols)

moses_app/hospital_stats_summary/views.py
# moses_app/hospital_stats_summary/views.py

from flask import Blueprint, render_template, redirect, url_for, session
from flask_login import login_user, login_required, logout_user
import flask_login
from moses_app import db
from moses_app.models import HospitalInfo, Hospitals
from moses_app import models
import datetime
import json
import pandas as pd

hospital_stats_summary_blueprint = Blueprint('hospital_stats_summary', __name__,
                                        template_folder='templates/hospital_stats_summary')

@hospital_stats_summary_blueprint.route('/hospital_stats_summary', methods=['GET', 'POST'])
def hospital_stats_summary():

    sql_query = """
    SELECT
        hospital_name
        , status
        , hospital_address
        , hospital_contact_num

        , num_confirmed_covid
        , num_pui

        , request_supplies
        , num_covid_kits
        , num_face_masks
        , num_surgical_gloves
        , num_alcohol
        , num_face_shield
        , num_hoods
        , num_shoe_covers
        , num_respirators

        , num_doctors_for_covid
        , num_nurses_for_covid
        , num_medstaff_for_covid

        , capacity_quarantine
        , notes

        , hospital_website
        , hospital_email
        , timestamp

    FROM HospitalInfo a
    LEFT JOIN Hospitals b
    ON a.hospital_id = b.id
    """

    table = db.engine.execute(sql_query)
    table = [row for row in table]

    columns = ['Hospital Name', 'Status', 'Address', 'Contact Num',
    'Num Confirmed COVID', 'Num PUI', 'Supplies Requested', 'Num COVID Kits',
    'Num Face Mask', 'Num Surgical Gloves', 'Num Alcohol', 'Num Face Shield',
    'Num Hoods', 'Num Shoe Covers', 'Num Respirators',
    'Num Doctors Assigned', 'Num Nurses Assigned', 'Num Med Staff Assigned',
    'Capacity to Quarantine', 'Notes',
    'Website',  'Email', 'Last Updated']

    df = pd.DataFrame(table)
    print(len(columns))
    print(df.shape)
    df.columns = columns


    df = df.groupby(by='Hospital Name').last().T.reset_index(drop=False)
    df.rename(columns={'index':'Hospital Name'}, inplace=True)
    df = df.T.reset_index().T

    num_cols = len(df.columns)
    df.columns = range(num_cols)
    df.to_csv('table.csv')

    table = df.to_dict()
    table = [{str(k):str(list(v.values())[i]) for k,v in table.items()} for i in range(len(df))]
    hospital_tables = table

    return render_template('hospital_stats_summary.html',
                    hospital_tables=json.dumps(hospital_tables),
                    num_cols=num_cols)

moses_app/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  </head>
  <style>
  .nav-item{
    font-size:120%;
  }
  </style>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top navbar-expand-md navbar-light bg-light">
    <!-- <a href="{{url_for('index')}}"><img src='static/img/logo.png'/></a> -->
    <div class="container-fluid">
        <div class="navbar-nav">
          <a href="{{url_for('index')}}" class="nav-item nav-link active">Home</a>
            <a href="{{url_for('dashboard')}}" class="nav-item nav-link">Dashboard</a>
            <a href="{{url_for('public_info')}}" class="nav-item nav-link">Information Portal</a>
            <a href="{{url_for('hospital_stats_summary.hospital_stats_summary')}}" class="nav-item nav-link">Hospitals Stats</a>            
            {% if current_user.is_authenticated %}
            <a href="{{url_for('hospital_info.hospital_info')}}" class="nav-item nav-link">Hospital Portal</a>
            {% else %}
            {% endif %}
        </div>
        <div class="navbar-nav ml-auto">
          {% if current_user.is_authenticated %}
            <a href="{{url_for('logout')}}" class="nav-item nav-link">Logout</a>
          {% else %}
          {% endif %}
        </div>
    </div>
</nav>
    {% block content %}

    {% endblock %}
  </body>
</html>

moses_app/templates/dashboard.html
{% extends "base.html" %}
{% block content %}

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <link rel="stylesheet" href="/static/css/bulma.min.css">
    <link rel='stylesheet' href="/static/css/style.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.10.1/bootstrap-table.min.js"></script>

    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>

    <style>
        #main-logo {
            margin-top: 20px;
            height: 300px;
            width: auto;
        }
        button {
            margin-top: 30px;
            margin-bottom: 30px;
        }
        #text-1 {
            /* font-weight: bold; */
            font-size: 40px;
        }

        body {
            margin: 0;            /* Reset default margin */
        }
        iframe {
            display: block;       /* iframes are inline by default */
            background: #000;
            border: none;         /* Reset default border */
            height: 100vh;        /* Viewport-relative units */
            width: 100vw;
        }

    </style>

  </head>

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class='container-fluid'>
    <div id='text-1'>DOH Dashboard</div>
    <!-- <p id='text-3'>Soon</p> -->
    <iframe src= 'https://ncovtracker.doh.gov.ph/'></iframe>
    </div>
  </body>
</html>

{% endblock %}

moses_app/templates/index.html
{% extends "base.html" %}
{% block content %}

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <link rel="stylesheet" href="/static/css/bulma.min.css">
    <link rel='stylesheet' href="/static/css/style.css">

    <style>
        button {
            margin-top: 30px;
            margin-bottom: 30px;
        }
        #text-1 {
            /* font-weight: bold; */
            font-size: 40px;
        }
        #text-2 {
            /* font-weight: bold; */
            font-size: 30px;
        }
        .img-responsive{
        max-width: 20%;
        height: auto;
      }

    </style>
</head>

<body>
    <div class="container">
        <div class='row'>
          <div class='column'>
            <img id="main-logo" class="img-fluid" alt="Responsive image" src='static/img/logo.png'/>
            <div id="text-2">A free-access health collaboration tool for COVID-19</div>
          </div>
        </div>
        <br>
        <div class='row-center'>
            <a href="{{url_for('dashboard')}}">
              <div id="text-1">Dashboard</div>
            </a>
            <a href="{{url_for('public_info')}}">
              <div id="text-1">Information Portal</div>
            </a>
            <a href="{{url_for('hospital_stats_summary.hospital_stats_summary')}}">
              <div id="text-1">Hospitals Statistics</div>
            </a>
            <a href="{{url_for('hospital_info.hospital_info')}}">
              <div id="text-1">Hospital Portal</div>
            </a>
        </div>
      </div>
</body>

{% endblock %}

moses_app/templates/login.html
{% extends "base.html" %}
{% block content %}

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <link rel="stylesheet" href="/static/css/bulma.min.css">
    <link rel='stylesheet' href="/static/css/style.css">

    <style>
      button {
          margin-top: 30px;
          margin-bottom: 30px;
      }
      #text-1 {
          /* font-weight: bold; */
          font-size: 40px;
      }
      #text-2 {
          /* font-weight: bold; */
          font-size: 30px;
      }
      .img-responsive{
      max-width: 20%;
      height: auto;
    }
    form{
      font-size:150%;
    }
    </style>
</head>

<body>
    <div class="container">
      <div class='column'>
        <img id="main-logo" class="img-fluid" alt="Responsive image" src='static/img/logo.png'/>
        <div id="text-2">A free-access health collaboration tool for COVID-19</div>
      </div>
        <div class="container">
          <div class='row'>
          <div class='column'>
          </div>
          <div class='column'>
            <form method="POST">
              <br>
              {{form.hidden_tag()}}
              {{form.hospital_user_name.label}}{{form.hospital_user_name(class_="form-control")}}
              {{form.password.label}}{{form.password(class_="form-control")}}
              <br>
              {{form.submit(class_="btn-success")}}
            </form>
          </div>
          <div class='column'>
          </div>
        </div>
        </div>

    </div>

</body>

{% endblock %}

moses_app/templates/public_info.html
{% extends "base.html" %}
{% block content %}

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <link rel="stylesheet" href="/static/css/bulma.min.css">
    <link rel='stylesheet' href="/static/css/style.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <style>
        #main-logo {
            margin-top: 20px;
            height: 300px;
            width: auto;
        }
        button {
            margin-top: 30px;
            margin-bottom: 30px;
        }
        #text-1 {
            /* font-weight: bold; */
            font-size: 40px;
        }

        body {
            margin: 0;            /* Reset default margin */
        }
        iframe {
            display: block;       /* iframes are inline by default */
            background: #000;
            border: none;         /* Reset default border */
            height: 100vh;        /* Viewport-relative units */
            width: 100vw;
        }

    </style>
  </head>


  <body>
    <div class='container'>
      <div id="text-1">Public Information Portal</div>
      <iframe src="https://docs.google.com/spreadsheets/d/e/2PACX-1vQ_yzYuSZMgBfe0H1l4w54DZ45sqxj6EEK5bB-n6h5iFWA3_4C-XHqu22-yXwcQIpwv-nbHrPSqt5SN/pubhtml?gid=2113110150&amp;single=true&amp;widget=true&amp;headers=false"></iframe>

    </div>
  </body>

{% endblock %}

moses_app/templates/register.html
{% extends "base.html" %}
{% block content %}

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <link rel="stylesheet" href="/static/css/bulma.min.css">
    <link rel='stylesheet' href="/static/css/style.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <style>
        #main-logo {
            margin-top: 20px;
            height: 300px;
            width: auto;
        }
        #bir-logo {
            margin-top: 60px;
            height: 80px;
            width: auto;
        }
        #text-1 {
            padding-top: 20px;
            font-size: 40px;
            font-weight: bold;
        }
        #main-container {
            /* margin-right: 300px;
            margin-left: 300px; */
            width: 1000px;
        }
        form {
            padding-top: 60px;
        }
        button {
            margin: 0;
            padding: 0;
        }
        .inline {
            display: inline-block;
        }
        #text-2 {
            width: 500px;
            word-wrap: break-word;
            text-align: justify;
        }
        #text-3 {
            padding-top: 10px;
            width: 500px;
            text-align: center;
        }
    </style>
</head>

<body>
    <div id="main-container" class="container">
        <div id="text-1">Hospital Registration</div>
          <div class="">
            <form method="POST">
              {{ form.hidden_tag() }}
              <div>
                  {{form.hospital_name.label}} <br> {{ form.hospital_name(class="form-control") }}
              </div>
              <br>
              <div>
                  {{ form.hospital_address.label }} <br> {{ form.hospital_address(class="form-control") }}
              </div>
              <br>
              <div class="">
                  {{ form.hospital_website.label }} <br> {{ form.hospital_website(class="form-control") }}
              </div>
              <br>
              <div class="">
                {{ form.hospital_contact_num.label }}
                <br> {{ form.hospital_contact_num(class="form-control") }}
              </div>
              <br>
              <div class="">
                {{ form.hospital_email.label }} <br> {{ form.hospital_email(class="form-control") }}
              </div>
              <br>
              <div class="">
                {{ form.hospital_user_name.label }} <br> {{ form.hospital_user_name(class="form-control") }}
              </div>
              <br>
              <div class="">
                {{ form.password.label }} <br> {{ form.password(class="form-control") }}
              </div>
              <br>
              <div class="">
                {{ form.password_confirm.label }} <br> {{ form.password_confirm(class="form-control") }}
              </div>
              <br>
              <div class="">
                {{ form.submit(class="button is-success") }}
              </div>
              <div class="">
                {{ warning }}

              </div>
            </form>
          </div>
    </div>
</body>

{% endblock %}